### ISSUE TITLE
path error on windows/msys

### ISSUE THREAD

**Issue by ladyada** [adafruit/cookiecutter-adafruit-circuitpython#148]
tried running cutter on both windows and msys with same error result:

```
C:\Users\ladyada\Dropbox\ArduinoSketches\libraries\Adafruit_IS31FL3741>cookiecutter gh:adafruit/cookiecutter-adafruit-circuitpython
You've downloaded C:\Users\ladyada\.cookiecutters\cookiecutter-adafruit-circuitpython before. Is it okay to delete and re-download it? [yes]: yes
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 616, in _rmtree_unsafe
    os.unlink(fullname)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\ladyada\\.cookiecutters\\cookiecutter-adafruit-circuitpython\\{% if cookiecutter.library_prefix %}{{ cookiecutter.library_prefix \uf07c capitalize }}_{% endif %}CircuitPython_{{ cookiecutter.library_name}}\\examples\\{{ cookiecutter.library_name \uf07c lower }}_simpletest.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ladyada\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts\cookiecutter.exe\__main__.py", line 7, in <module>
  File "c:\Users\ladyada\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\Users\ladyada\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\Users\ladyada\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\Users\ladyada\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\Users\ladyada\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\cookiecutter\cli.py", line 140, in main
    cookiecutter(
  File "c:\Users\ladyada\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\cookiecutter\main.py", line 67, in cookiecutter
    repo_dir, cleanup = determine_repo_dir(
  File "c:\Users\ladyada\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\cookiecutter\repository.py", line 110, in determine_repo_dir
    cloned_repo = clone(
  File "c:\Users\ladyada\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\cookiecutter\vcs.py", line 95, in clone
    clone = prompt_and_delete(repo_dir, no_input=no_input)
  File "c:\Users\ladyada\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\cookiecutter\utils.py", line 99, in prompt_and_delete
    rmtree(path)
  File "c:\Users\ladyada\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\cookiecutter\utils.py", line 34, in rmtree
    shutil.rmtree(path, onerror=force_delete)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 618, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\Users\ladyada\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\cookiecutter\utils.py", line 25, in force_delete
    os.chmod(path, stat.S_IWRITE)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\ladyada\\.cookiecutters\\cookiecutter-adafruit-circuitpython\\{% if cookiecutter.library_prefix %}{{ cookiecutter.library_prefix \uf07c capitalize }}_{% endif %}CircuitPython_{{ cookiecutter.library_name}}\\examples\\{{ cookiecutter.library_name \uf07c lower }}_simpletest.py'
```

**Comment by tannewt** [comment]
Does it work if you delete `C:\Users\ladyada\.cookiecutters\` manually?

**Comment by ladyada** [comment]
ooh that helped - odd because i thought i'd already tried it! will reopen next time i make a library :)
