### ISSUE TITLE
Running pre-commit yields error

### ISSUE THREAD

**Issue by makermelissa** [adafruit/cookiecutter-adafruit-circuitpython#90]
The error displayed is:
```
error: pathspec 'latest' did not match any file(s) known to git
```

Here's the log sections already nicely formatted for git :)

### version information

```
pre-commit version: 2.8.2
sys.version:
    3.9.0 (default, Nov 11 2020, 09:57:57)
    [Clang 12.0.0 (clang-1200.0.32.21)]
sys.executable: /usr/local/opt/python@3.9/bin/python3.9
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/bin/git', 'checkout', 'latest')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: pathspec 'latest' did not match any file(s) known to git

```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pre_commit/store.py", line 183, in clone_strategy
    self._shallow_clone(ref, _git_cmd)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/store.py", line 165, in _shallow_clone
    git_cmd('-c', git_config, 'fetch', 'origin', ref, '--depth=1')
  File "/usr/local/lib/python3.9/site-packages/pre_commit/store.py", line 180, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/local/bin/git', '-c', 'protocol.version=2', 'fetch', 'origin', 'latest', '--depth=1')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    fatal: couldn't find remote ref latest


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pre_commit/error_handler.py", line 65, in error_handler
    yield
  File "/usr/local/lib/python3.9/site-packages/pre_commit/main.py", line 375, in main
    return run(args.config, store, args)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/commands/run.py", line 377, in run
    for hook in all_hooks(config, store)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/repository.py", line 210, in all_hooks
    return tuple(
  File "/usr/local/lib/python3.9/site-packages/pre_commit/repository.py", line 213, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/repository.py", line 188, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/repository.py", line 154, in _cloned_repository_hooks
    manifest_path = os.path.join(store.clone(repo, rev), C.MANIFEST_FILE)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/store.py", line 187, in clone
    return self._new_repo(repo, ref, deps, clone_strategy)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/store.py", line 144, in _new_repo
    make_strategy(directory)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/store.py", line 185, in clone_strategy
    self._complete_clone(ref, _git_cmd)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/store.py", line 158, in _complete_clone
    git_cmd('checkout', ref)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/store.py", line 180, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/usr/local/lib/python3.9/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/local/bin/git', 'checkout', 'latest')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: pathspec 'latest' did not match any file(s) known to git
```

**Comment by makermelissa** [comment]
This appears to have been caused by #89. When I pushed to github, I saw this additional line:
```
[INFO] Initializing environment for https://github.com/python/black.
```

**Comment by makermelissa** [comment]
Changing `latest` to `stable` seems to fix it.
